.TH "debuild-pbuilder" 1 "2002 Sep 6" "Debian" "pbuilder"
.SH NAME
debuild-pbuilder \- A "debuild" wrapper to satisfy build-dependency before debuild
.SH SYNOPSIS
.BI "debuild-pbuilder
.SH DESCRIPTION
A wrapper to "debuild" program that 
does Build-Dependency satisfaction.

.SH OPTIONS

See debuild manpage for details.

.SH "SEE ALSO"
.RI "debuild (" 1 ")"

