.TH "debuild-pbuilder" 1 "2002 Sep 25" "Debian" "pbuilder"
.SH "NAME"
debuild-pbuilder \- A "debuild" wrapper to satisfy build-dependency before debuild
.SH SYNOPSIS
.BI "debuild-pbuilder"

.SH "DESCRIPTION"
A wrapper to "debuild" program that 
does Build-Dependency satisfaction.

.SH "OPTIONS"

See debuild manpage for details.

.SH "AUTHOR"
Initial coding, and main maintenance is done by 
Junichi Uekawa <dancer@debian.org>.

The homepage is available at
.B "http://www.netfort.gr.jp/~dancer/software/pbuilder.html"

.SH "SEE ALSO"
.RI "debuild (" 1 ")"

