.TH "debuild-pbuilder" 1 "2002 Sep 25" "Debian" "pbuilder"
.SH "NAME"
debuild-pbuilder \- A "debuild" wrapper to satisfy build-dependency before debuild
.SH SYNOPSIS
.BI "debuild-pbuilder"

.SH "DESCRIPTION"
A wrapper to "debuild" program that 
does Build-Dependency satisfaction.

.SH "OPTIONS"

See debuild manpage for details.

.SH "EXAMPLES"

.TP
.B "debuild-pbuilder"
Satisfy build-dependency and run debuild.

.nf
$ debuild-pbuilder
W: /home/dancer/.pbuilderrc does not exist
 -> Attempting to parse the build-deps : pbuilder-satisfydepends,v 1.29 2006/11/06 20:20:56 lool Exp $
 -> Considering build-dep debhelper (>= 4.1.0)
   -> Trying debhelper
	.
	.
.hy



.SH "AUTHOR"
Initial coding, and main maintenance is done by 
Junichi Uekawa <dancer@debian.org>.

The homepage is available at
.B "\%http://pbuilder.alioth.debian.org"

.SH "SEE ALSO"
.BR "/usr/share/doc/pbuilder/pbuilder-doc.html" ", "
.BR "debuild" "(1)" 

