.TH "pbuilder" 1 "2001 Aug 25" "Debian" "pbuilder"
.SH NAME
pbuilder \- personal package builder
.SH SYNOPSIS
.BI "pbuilder create [" "options" "]"
.PP
.BI "pbuilder update [" "options" "]"
.PP
.BI "pbuilder build [" "options" "] " ".dsc-file"
.PP
.BI "pbuilder clean"
.PP
.BI "pbuilder login"
.SH DESCRIPTION
Front end program to the 
.B "pbuilder"
suite of programs, used for creating and maintaining chroot environment 
and building Debian package in the chroot environment.
.SH OPTIONS
.TP
.B "create"
Creates a 
.B "base.tgz" 
for the specified distribution.

.TP
.B "update"
Updates the 
.B "base.tgz"
for the specified distribution.

.TP
.B "build"
Builds the package specified by
.I ".dsc-file"
in the chroot environment created using the 
.B "base.tgz"

.TP
.B "clean"
Cleans up the directory specified by the configuration
.B "BUILDPLACE"
and
.B "APTCACHE"
specified in 
.I "/etc/pbuilderrc"

.TP
.B "login"
Logs into the chroot, and cleaned up afterwards.
Any changes you make will not be kept.
.TP
.BI "--basetgz [" "basetgz-location" "]"
Specifies the location of 
.B "base.tgz"
.TP
.BI "--buildplace [" "location of build" "]"
Specifies the location where building and 
.B "base.tgz"
updating and creation takes place. This is 
a temporary work directory.
.TP
.BI "--buildresult [" "location to put build result" "]"
Specifiees the location the build result gets into after building.
The deb files and other files that have resulted from build 
is copied there.
.TP
.BI "--mirror [" "mirror location" "]"
Specifies the url of Debian mirror to be 
specified in 
.B "sources.list"
inside the chroot.
This option is only valid when distribution is being specified, for 
update and build targets.
The format is something like:
.I "http://http.us.debian.org/debian" 
which should point to your favorite mirror.
.TP
.BI "--nonusmirror [" "mirror location" "]"
The non-US mirror, specified like the 
.B "--mirror"
option
.TP
.BI "--othermirror [" "apt deb line " "|" " other deb lines... " "]"
The lines which is added to the sources.list, delimited with 
.B "|"
.TP
.BI "--http-proxy [" "proxy" "]"
Specifies the http proxy url. Something like
.B "http://xxx.xxx.xxx.xxx:8080/"
should do. 
.TP
.BI "--distribution [" "distribution" "]"
Specifies the distribution used. Currently the supported values are
.B "sid"
and 
.B "woody".
.TP
.BI "--removepackages [" "packages to remove" "]"
Removes the packages on creating the 
.BI "base.tgz" "."
Use this option to remove potentially dangerous or undesirable
packages, like
.B "lilo"
which nobody will need to have inside a chroot.
.SH "FILES"
.TP
.I "/etc/pbuilderrc"
The configuration file for pbuilder.
.SH AUTHOR
Junichi Uekawa <dancer@debian.org>
.SH "SEE ALSO"
.RI "pbuilderrc (" 5 ") "

