.TH "pbuilder" 8 "2005 Jul 10" "Debian" "pbuilder"
.SH NAME
pbuilder \- personal package builder
.SH SYNOPSIS
.BI "pbuilder create [" "options" "]"
.PP
.BI "pbuilder update [" "options" "]"
.PP
.BI "pbuilder build [" "options" "] " ".dsc-file"
.PP
.BI "pbuilder execute [" "options" "] -- " "script [" "script options" "]"
.PP
.BI "pbuilder clean"
.PP
.BI "pbuilder login [" "options" "]"
.SH DESCRIPTION
Front end program to the 
.B "pbuilder"
suite of programs, used for creating and maintaining chroot environment 
and building Debian package in the chroot environment.

.SH "COMMANDS"

.TP
.B "create"
Creates a 
.B "base.tgz" 
for the specified distribution.

.TP
.B "update"
Updates the 
.B "base.tgz"
for the specified distribution.
Also, by specifying the 
.B "\-\-override\-config"
option, it is possible to install a new apt-line using 
the given options and settings in the configuration file 
for the base.tgz.

For example, to switch the distribution of an existing
base.tgz to etch, specify the
.B "\-\-distribution etch \-\-override\-config" 
options to update.

.TP
.B "build"
Builds the package specified by
.I ".dsc-file"
in the chroot environment created using the 
.B "base.tgz"

.TP
.B "clean"
Cleans up the directory specified by the configuration
.B "BUILDPLACE"
and
.B "APTCACHE"
specified in 
.I "/etc/pbuilderrc"

.TP
.B "login"
Logs into the chroot, and cleaned up afterwards.
Any changes you make will not be kept.
Only use this for temporary and debugging purposes.
Do not bind-mount filesystems directly inside the chroot.
Use
.B "\-\-bindmounts" 
option to mount.

.TP
.B "execute"
Execute a script or command inside the chroot,
in a similar manner to 
.B "login"

The file specified in the command-line argument will be 
copied into the chroot, and invoked.

The remaining arguments are passed on to the script.

.TP
.B "dumpconfig"
Dumps configuration information, used for debugging.

.TP
.B "debuild"
Builds a Debian package from the Debian source directory.
There needs to be a 
.I "debian/"
directory in the current directory.

This command is a convenience script, 
and it does not accept most command-line options.
This may change in the future.

.SH "OPTIONS"

The command is followed by options of the form
.BI "\-\-" "option name"
which will modify the semantics as explained below.
They are applied from left-to-right, and when there are 
conflicting options, the rightmost options will have effect.

.TP
.BI "\-\-basetgz [" "basetgz-location" "]"
Specifies the location of 
.B "base.tgz"

This option will define the default distribution and 
apt-lines when used in
.B "pbuilder update"
and 
.B "pbuilder create"

.TP
.BI "\-\-buildplace [" "location of build" "]"
Specifies the location where building and 
.B "base.tgz"
updating and creation takes place. This is 
a temporary work directory.

A subdirectory of that directory using the current PID of the
process is used.

.TP
.BI "\-\-buildresult [" "location to put build result" "]"
Specifies the location the build result gets into after building.
The deb files and other files that have resulted from build 
is copied there.
Note that the default value is not the current directory,
or 
.B ".."
but another place, 
.B "/var/cache/pbuilder/result"
This is to avoid
overwriting already existing deb files with
the newly generated ones.

.TP
.BI "\-\-mirror [" "mirror location" "]"
Specifies the URL of Debian mirror to be 
specified in 
.B "sources.list"
inside the chroot.
This option is only valid when distribution is being specified, for 
update and build targets.
The format is something like:
.I "http://http.us.debian.org/debian" 
which should point to your favourite mirror.

This option can optionally be omitted, and left blank,
in which case, this part is skipped.

Note that these URLs specified to pbuilder will be used from within
the chroot, and specifying 
.B "file:/somewhere/"
will most probably fail.

.TP
.BI "\-\-othermirror [" "deb http://xxx/xxx/ ./ " "|" " other deb lines... " "]"
The lines which is added to the sources.list, delimited with 
.B "|"
Like 
.B "deb http://local/mirror stable main|deb file:/usr/local/mirror ./"

The deb lines here are the ones that will appear at the top of the 
.B "sources.list"
inside the chroot.
Be sure to follow the syntax rules of
.RI "sources.list (" 5 ")."
These lines appear at the beginning of the
constructed sources file, so this is the place to list your
.B "local"
mirror sites; apt will then use them in preference to the ones 
listed in 
.B "\-\-mirror".

These options are only valid when
.B "\-\-override\-config"
option is specified in 
.B "update"
target, or when
.B "pbuilder create"
is being called.

.TP
.BI "\-\-http\-proxy [" "proxy" "]"
Specifies the http proxy URL. Something like
.B "http://xxx.xxx.xxx.xxx:8080/"
should do. 
.TP
.BI "\-\-distribution [" "distribution" "]"
Specifies the distribution used. Currently the supported values are
.B "sid"
.B "sarge"
.B "etch"
and 
.B "experimental".

This option is only effective for 
.B "pbuilder create" 
or when 
.B "pbuilder update"
is specified with 
.B "\-\-override\-config"
option.

.TP
.BI "\-\-aptcache [" "location of retrieved package files" "]"
Specifies the location where the packages downloaded by apt should
be cached. Use
.B "\-\-aptcache """""
if you want caching to be turned off.

.TP
.BI "\-\-removepackages [" "packages to remove" "]"
Removes the packages on creating the 
.BR "base.tgz" "."
Use this option to remove potentially dangerous or undesirable
packages, like
.B "lilo"
which nobody will need to have inside a chroot.

Packages should be specified in a space-delimited manner, 
surrounded in double quotations, like 
.B """lilo gcc mawk"""

.TP
.BI "\-\-extrapackages [" "packages to add" "]"
Adds packages specified as an addition to the default,
which is 
.B "build-essential"
by default.
This is used in 
.B "build"
and 
.B "create"
(after successfully creating the initial chroot)
and 
.BR "update" .

The packages should be specified as a space-delimited list.

.TP
.BI "\-\-configfile [" "configuration file to load" "]"
Loads the configuration file.

\" START OF hookdir description

.TP
.BI "\-\-hookdir [" "location of user scripts" "]"
Specifies the location where scripts for user intervention during
the create and update process are stored. Currently scripts are
executed at only one point, on exit from the chrooted environment,
just before either a create or a build regenerated the base.tgz
file. The script names must be in the form 
.B "X<digit><digit><whatever-else-you-want>"
much like boot scripts. The scripts must be executable and may
be either binaries or interpreted scripts. If it is a script
in other than Bourne Shell or Perl, it is up to the user to
ensure the interpreter was previously installed in the chrooted
environment. Files ending in ~ or .bak are ignored.

Although it may not seem necessary, 
.B "pbuilder update" 
does not invoke the hooks if 
.B "\-\-hookdir"
is empty, so if you want to avoid running hooks,
run pbuilder with
.B "\-\-hookdir """""

If there is a distribution hook, for example, if 
there was a file 
.B "sid"
inside the hook directory, and the script was creating the 
chroot for
.B "sid"
distribution, pbuilder will call debootstrap with that 
as the 4th parameter in the chroot creation process.
This allows for use of custom debootstrap hook script.

.B "A<digit><digit><whatever-else-you-want>"
is for 
.B build 
target. 
It is executed before build starts; after
unpacking the build system, and unpacking the source,
and satisfying the build-dependency.

.B "B<digit><digit><whatever-else-you-want>"
is executed after build system finishes building,
successfully, before copying back the build result.

.B "C<digit><digit><whatever-else-you-want>"
is executed after build failure, before cleanup.

.B "D<digit><digit><whatever-else-you-want>"
is executed before unpacking the source inside the chroot,
after setting up the chroot environment.
Create $TMP, and $TMPDIR if necessary.

This is called before build-dependency is satisfied.
Also useful for calling 
.B "apt-get update"

.B "E<digit><digit><whatever-else-you-want>"
is executed after
.B "pbuilder update"
 and
.B "pbuilder create"
finishes apt-get work with the chroot, 
before umounting kernel file systems (/proc) and 
creating the tarball from the chroot.

.B "F<digit><digit><whatever-else-you-want>"
is executed just before user logs in, or 
program starts executing, after chroot is created 
in 
.B login
or 
.B execute
target.

.B "G<digit><digit><whatever-else-you-want>"
is executed just after debootstrap finishes,
and configuration is loaded, and pbuilder starts mounting /proc and invoking 
.B "apt-get install"
in 
.B create
target.

\" End of hookdir description


.TP
.BI "\-\-debemail [" "maintainer-name <email-address>" "]"

Specifies that dpkg-buildpackage be called with
.BI "-m" "maintainer-name <email-address>"
instead of default value specified in the environment
variable, or pbuilderrc

.B "This option is almost obsolete, use \-\-debbuildopts instead"

.TP
.BI "\-\-debbuildopts [" "options" "]"

List of options that are passed on to dpkg-buildpackage. Overrides
any value given in DEBBUILDOPTS as specified in
pbuilderrc.

.TP
.BI "\-\-logfile [" "file to log" "]"
Specifies the logfile to create. 
The messages generated during execution will be written to the file, 
instead of messages coming to the 
standard output.

.TP
.BI "\-\-pkgname\-logfile"
Alternative option to 
.B "\-\-logfile"
option. 
Automatically creates a logfile that is named by the .dsc file name,
only really applicable for 
.B build
target.

The file extension is specified by 
.B "PKGNAME_LOGFILE_EXTENTION"
in 
.B "pbuilderrc"

.TP
.BI "\-\-aptconfdir [" "APT configuration directory to use" "]"
Uses the apt configuration file found in the specified directory 
as the chroot configuration.
.B "/etc/apt"
is one example, so that  the same configuration can be used inside the
chroot.

This option overrides other options, and may cause some inconsistency
problems.

.TP
.BI "\-\-timeout [" "timeout in sleep time" "]"
Time out building after sleeping set time.
Specify something like
.B "\-\-timeout 10h"
in the command line.
Default is no timeout.


.TP
.BI "\-\-override\-config"

Specify to use different apt set up inside the chroot than it was used for creating the 
base.tgz.
Specify this when you want to do pbuilder update with a different distribution
target set up.


.TP
.BI "\-\-binary\-arch"

Specify to build architecture specific targets instead of all targets.
Setting
.B "\-\-debbuildopts"
after this option will re-set some parts of the effect.

Use this option rather than using 
.B "\-\-debbuildopts -B"

.TP
.BI "\-\-no\-targz"
Not using base.tgz for operation.
The
.B "\-\-buildplace"
will not be deleted and reconstructed from
a 
.B .tar.gz
file.
Also, 
.B "pbuilder"
will not add its process ID to the
.B "\-\-buildplace"
as it usually would.

Useful when experimenting with 
chroots, or trying to create chroots outside control
of
.B "pbuilder."

.TP
.BI "\-\-preserve\-buildplace"
Do not clean the
.B "\-\-buildplace"
if it has the same contents as the
.B .tar.gz
file, and no modifications are done.

For preserving the build place for
.B "create"
and 
.B "update"
targets, see
.B "--debug"
option.

As with
.BR "\-\-no\-targz" ","
suppresses appending
.BR "pbuilder" "'s"
process ID to the
.BR "\-\-buildplace" "."

This is useful if you want to attempt to build a large number of
packages successively, but you expect that many of them cannot have
their build dependencies satisfied.

It will clean up the build place on failure, 
or after a successful build.

.TP
.BI "\-\-bindmounts " "bind-mount-points"
Bind-mount the specified directories to inside the chroot.
.I "bind-mount-points"
is a space-delimited list of directories to bind-mount.

.TP
.BI "\-\-debug"

Turn on Debug mode of pbuilder, to be verbose about errors,
and try to avoid cleanup processing when error happens in 
.B update
 and
.B create
targets.

.TP
.BI "\-\-debootstrapopts " "\-\-variant=buildd"
Add extra command-line options to debootstrap.

.TP
.BI "\-\-debootstrap " "debootstrap"
Use specified debootstrap implementation as debootstrap.
Known implementations are
.B cdebootstrap
and
.B debootstrap

.TP
.BI "\-\-save\-after\-login "
.TP
.BI "\-\-save\-after\-exec "
Save the chroot image after exiting from the chroot instead of 
deleting changes.
Effective for 
.B login
and 
.B execute
session.


.TP
.BI "\-\-autocleanaptcache"
Clean apt cache automatically, to run apt-get autoclean to only 
keep the packages which are required for the version of Debian.
This is useful when you keep a aptcache directory for each distribution
and want to keep the size of the aptcache down.

.TP
.BI "\-\-help"

Show a brief help message.


.SH "FILES"
.TP
.I "/etc/pbuilderrc"
The system-wide configuration file for pbuilder.
.TP
.I "/usr/share/pbuilder/pbuilderrc"
The default settings for pbuilder, used as fallback for all 
values that is not specified in
.B "/etc/pbuilderrc."
.TP
.I "${HOME}/.pbuilderrc"
The personal configuration file for pbuilder, which overrides
settings set in other configuration files.

.SH "BUGS"
This program is starting to have too many options already.

.SH "AUTHOR"
Initial coding, and main maintenance is done by 
Junichi Uekawa <dancer@debian.org>.
User hooks code added by Dale Amon <amon@vnl.com>

The homepage is available at
.B "\%http://www.netfort.gr.jp/~dancer/software/pbuilder.html"

.SH "SEE ALSO"
.RI "pdebuild (" 1 "), "
.RI "pbuilderrc (" 5 ") "


\"  LocalWords:  buildresult
