#! /bin/bash
# pbuilder by Junichi Uekawa <dancer@debian.org> 2001 Aug 25
# Copyright 2001,2002 Junichi Uekawa
#Distributed under GPL version 2 or later

set -e 

# export this so that programs know which command line
# operation is currently done
export PBCURRENTCOMMANDLINEOPERATION="$1"

case "$1" in
    create)
	shift;
	/usr/lib/pbuilder/pbuilder-createbuildenv "$@"
	;;
    update)
	shift ;
	/usr/lib/pbuilder/pbuilder-updatebuildenv "$@"
	;;
    build)
	shift ;
	/usr/lib/pbuilder/pbuilder-buildpackage "$@"
	;;
    clean)
	shift;
	. /usr/lib/pbuilder/pbuilder-checkparams
	if [ -n "$BASEBUILDPLACE" ]; then 
	    echo "Cleaning [$BASEBUILDPLACE]"
	    rm -rf "$BASEBUILDPLACE"/* || true
	fi
	if [ -n "$APTCACHE" ]; then
	    echo "Cleaning [$APTCACHE]"
	    rm -rf "$APTCACHE"/* || true
	fi
	;;
    login)
	shift 
	. /usr/lib/pbuilder/pbuilder-checkparams
	extractbuildplace
	trap umountproc_cleanbuildplace exit
	if [ "${INTERNAL_BUILD_UML}" = "yes" ]; then
	    echo " -> entering the shell"
	else
	    echo " -> entering the shell
DO NOT bind mount file system inside, they will be cleaned.
File extracted to: $BUILDPLACE
"
	fi
	chroot "$BUILDPLACE" bin/bash
	;;
    execute)
	# try to execute arbitrary program.
	shift
	. /usr/lib/pbuilder/pbuilder-checkparams
	EXECPROGRAM="$1"
	if [ ! -f "${EXECPROGRAM}" ]; then
	    echo "Command line parameter [$EXECPROGRAM] does not exist" >&2
	    exit 1;
	fi;
	extractbuildplace
	trap umountproc_cleanbuildplace exit
	RUNNAME="$BUILDPLACE/run"
	cat "$EXECPROGRAM" > "$RUNNAME"
	chmod a+x "$RUNNAME"
	chroot "$BUILDPLACE" /run
	;;
    *)
	. /usr/lib/pbuilder/pbuilder-modules
	showhelp
	;;
esac

