#! /bin/bash
# pbuilder by Junichi Uekawa <dancer@debian.org> 2001 Aug 25
# Copyright 2001,2002 Junichi Uekawa
#Distributed under GPL version 2 or later

set -e 

# export this so that programs know which command line
# operation is currently done
export PBCURRENTCOMMANDLINEOPERATION="$1"

case "$1" in
    create)
	shift;
	/usr/lib/pbuilder/pbuilder-createbuildenv "$@"
	;;
    update)
	shift ;
	/usr/lib/pbuilder/pbuilder-updatebuildenv "$@"
	;;
    build)
	shift ;
	/usr/lib/pbuilder/pbuilder-buildpackage "$@"
	;;
    clean)
	shift;
	. /usr/lib/pbuilder/pbuilder-checkparams
	if [ -n "$BUILDPLACE" ]; then 
	    echo "Cleaning [$BUILDPLACE]"
	    rm -rf "$BUILDPLACE"/* || true
	fi
	if [ -n "$APTCACHE" ]; then
	    echo "Cleaning [$APTCACHE]"
	    rm -rf "$APTCACHE"/* || true
	fi
	;;
    login)
	shift 
	. /usr/lib/pbuilder/pbuilder-checkparams
	extractbuildplace
	trap umountproc_cleanbuildplace exit
	echo " -> entering the shell"
	chroot "$BUILDPLACE" bin/bash
	;;
    *)
	. /usr/lib/pbuilder/pbuilder-modules
	showhelp
	;;
esac

