#! /bin/bash

set -e 

. /usr/lib/pbuilder/pbuilder-checkparams
. /usr/lib/pbuilder/pbuilder-runhooks


CHROOTEXEC="chroot $BUILDPLACE "

test -n "$DISTRIBUTION" && echo "Upgrading for distribution $DISTRIBUTION" 

extractbuildplace
trap umountproc_cleanbuildplace exit

if [ -n "$HOOKDIR" ]; then
    loadhooks
fi
echo "Refreshing the base.tgz "
echo " -> upgrading packages"
$CHROOTEXEC /usr/bin/apt-get update
$CHROOTEXEC /usr/bin/dpkg --purge lilo
$CHROOTEXEC /usr/bin/apt-get -y dist-upgrade
$CHROOTEXEC /usr/bin/apt-get -y install build-essential dpkg-dev apt $EXTRAPACKAGES
$CHROOTEXEC /usr/bin/apt-get clean 

if [ -n "$HOOKDIR" ]; then
    executehooks "X"
    unloadhooks
fi
umountproc
trap cleanbuildplace exit
echo " -> creating base.tgz"
(cd "$BUILDPLACE"; tar cfz "$BASETGZ" *)
cleanbuildplace
