.TH "pbuilder-user-mode-linux" 1 "2002 Sep 17" "Debian" "pbuilder"
.SH NAME
pbuilder-user-mode-linux \- personal package builder in UML
.SH SYNOPSIS
.BI "pbuilder-user-mode-linux create [" "options" "]"
.PP
.BI "pbuilder-user-mode-linux update [" "options" "]"
.PP
.BI "pbuilder-user-mode-linux build [" "options" "] " ".dsc-file"
.PP
.BI "pbuilder-user-mode-linux execute [" "options" "] " "script"
.PP
.BI "pbuilder-user-mode-linux login [" "options" "]"
.SH DESCRIPTION
Front end program to the 
.B "pbuilder"
suite of programs, used for creating and maintaining user-mode-linux environment
and building Debian package within the user-mode-linux virtual machine 
environment.
.SH OPTIONS
.TP
.B "create"
Creates a user-mode-linux root image 
for the specified distribution using 
.B rootstrap
software

.TP
.B "update"
Updates the 
user-mode-linux root image
for the specified distribution.
Also, by specifying the 
.B "--distribution"
option, it is possible to switch the distribution.
Specify a dummy distribution value 
even for custom apt config files.

.TP
.B "build"
Builds the package specified by
.I ".dsc-file"
within the user-mode-linux environment.

.TP
.B "login"
Invokes shell within UML.

.TP
.B "execute"
Invokes a command or script inside UML.
.B "execute"
will copy the specified file into the UML system,
and run it.

.TP
.BI "--uml-image [" "UML image" "]"
Specify the UML image to use.

.TP
.BI "--eth0 [" "uml option for eth0" "]"
Specify this option as parameter to UML.

.TP
.BI "--uml-ip [" "IP inside UML" "]"
Specify this to set the IP inside UML.

.TP
.BI "--uml-netmask [" "netmask" "]"
.TP
.BI "--uml-network [" "network" "]"
.TP
.BI "--uml-broadcast [" "broadcast" "]"
.TP
.BI "--uml-gateway [" "gateway" "]"
.TP
.BI "--uml-image [" "UML image" "]"
Specify the UML image to use.

.TP
.BI "--mount-tmpfs [" "yes" "]"
Specify whether to mount tmpfs inside UML chroot.

.TP
.BI "--uml-hostname [" "uml-host" "]"
The hostname inside uml.

.TP
.BI "--distribution [" "sid" "]"
Specify the distribution.
see pbuilder.8

.TP
.BI "--binary-arch"
Specify only to build binary-arch targets.
see pbuilder.8

.TP
.BI "--timeout " "timeouttime"
Timeout build after specified time.
see pbuilder.8

.TP
.BI "--configfile " "config file to read"
Makes pbuilder to read the config file inside UML.
pbuilder-user-mode-linux itself would be affected by the contents of the 
config file.

.TP
.BI "--hookdir " "location of hooks"
Makes pbuilder use the specified hookdir inside UML.

.TP
.BI "--aptconfdir " "apt configuretion directory"
Makes pbuilder to use specified apt configuration directory instead of 
other settings. See pbuilder.8

.TP 
.BI "--override-config"
Specify this option along with
.B --distribution 
to switch distribution using 
.B "pbuilder-user-mode-linux update"

.TP 
.BI "--logfile " "logfilename"
Specify this option to make the output go to 
.I logfilename
instead of standard output.

.TP 
.BI "--buildresult " "/dir/to/build/result"
The directory where build result is placed to

.TP
.BI "--uml-debugmode"
Enable tracing of shell scripts used by pbuilder-user-mode-linux.

.TP 
.BI "--bindmounts " "/dir/to/bind-mount"
Bind-mount the directory inside the chroot inside the user-mode-linux.

.SH "NOTES"
For 
.B build
and
.B login
targets, 
.B pbuider-user-mode-linux
will try to use COW devices.

Inside user-mode-linux, pbuilder-uml will mount 
tmpfs as 
.B /tmp
to avoid temporary file race conditions with outside of UML.
This may cause problems trying to use files in /tmp directory.

.SH "FILES"
.TP
.I "/etc/pbuilderrc"
The system-wide configuration file for pbuilder.
.TP
.I "/usr/share/pbuilder/pbuilderrc"
The default settings for pbuilder, used as fallback for all 
values that is not specified in
.B "/etc/pbuilderrc."
.TP
.B "/etc/pbuilder/pbuilder-uml.conf"
System-wide configuration file for pbuilder-uml, 
it will take priority over pbuilder configurations.
.TP
.B "/usr/share/pbuilder/pbuilder-uml.conf"
Software-default configuration file for pbuilder-uml.
.TP
.B "${HOME}/.pbuilderrc"
User-default configuration file.
.SH "SEE ALSO"
.RI "pdebuild (" 1 "), "
.RI "pbuilder (" 8 "), "
.RI "rootstrap (" 1 "), "
.RI "linux (" 1 "), "
.RI "pbuilderrc (" 5 "), "
.RI "pbuilder-uml.conf (" 5 ") "



