.TH "pbuilderrc" 5 "2002 Sep 25" "Debian" "pbuilder"
.SH NAME
pbuilderrc \- configuration files for personal package builder
.SH DESCRIPTION
.B "/etc/pbuilderrc" 
contains default values used in the 
.B "pbuilder"
program invocation.
.PP
The file itself is sourced by a shell script, so
it is required that the file conforms to shell script conventions.
.SH "FORMAT"
.TP
.BI "BASETGZ=" "/var/cache/pbuilder/base.tgz"
Specifies the default location for the archived 
chroot image to be created and used.
This is overridden with the option 
.BR "--basetgz" "."
.TP
.BI "EXTRAPACKAGES=" "gcc3.0-athlon-builder"
Specifies extra packages which the system should install
in the chroot on 
.BR "pbuilder create" "."
Also this is installed on
.B "pbuilder build"

.TP
.BI "export DEBIAN_BUILDARCH=" "athlon"
Uses this variable as 
.BR "DEBIAN_BUILDARCH" "."
This trick can be used for other environmental variables as well.
.TP
.BI "BUILDPLACE=" "/var/cache/pbuilder/build/"
The default place which the chroot is constructed.
.B pbuilder
will use the directory 
.BR "$BUILDPLACE$$" "."
which means, that it will use the directory and the 
PID to determine the directory to use.
This should obtain an unique directory for 
concurrent runs of pbuilder in one machine.
This is not guaranteed to happen on network shared drives,
so be aware of this fact when playing with this option
on NFS shared beowulf clusters.
Change it to something like 
.I "/var/cache/pbuilder/build/$HOSTNAME/"
when doing such a thing.

.B "pbuilder clean"
cleans up this directory.
.TP
.BI "MIRRORSITE=" "http://www.jp.debian.org/debian"
Specify the mirror site which contains the
main Debian distribution.

Note that you cannot really use
.B "file:/" 
kind of URL, because the location needs to be accessible from within
the chroot.

.TP
.BI "NONUSMIRRORSITE=" "http://www.jp.debian.org/debian-non-US"
Specify the mirror site which contains
.B "non-US"
distribution.

.TP
.BI "OTHERMIRROR=" """deb http://www.home.com/updates/ ./"""
Add other lines which you want to have added to
.B "/etc/apt/sources.list" 
here.
The contents of this variable are inserted into the
.B "/etc/apt/sources.list" 
verbatim inside the chroot, so be sure to follow the syntax rules of
.RI "sources.list (" 5 ")."
These lines appear at the beginning of the
constructed sources file, so this is the place to list your
.B local
mirror sites; apt will then use them in preference to the ones 
listed in 
.B "MIRRORSITE"
and
.B "NONUSMIRRORSITE".

To make changes on mirror site effective on 
.B update
.B "--override-config"
needs to be specified.

.TP
.BI "export http_proxy=" "http://your-proxy:8080/"
Defines the proxy for http connection.
.TP
.BI "USEPROC=" "yes"
Specify 
.B yes
when it is desired to mount
.B /proc
interface. It is usually a good idea, since there are many
software which fail miserably when there is no
.B /proc
being mounted.

.TP
.BI "USEDEVPTS=" "yes"
Specify
.B yes
when it is desired to mount
.B /dev/pts
interface. It is usually a good idea, since there
are many software which fail miserably when there is no
.B /dev/pts
being mounted.

.TP
.BI "BUILDRESULT=" "/var/cache/pbuilder/result/"
Specify the default directory which the build result will
be copied over to after the building.

This option is not effective for 
.B pdebuild 
command. Use 
.B "--buildresult"
option instead.

.TP
.BI "DISTRIBUTION=" "sid"
Specify the default distribution to use.
This option only affects when doing
.B "pbuilder create" 
or when
.B "--override-config"
is specified for 
.B "pbuilder update" 
option.

.TP
.BI "APTCACHE=" "/var/cache/pbuilder/aptcache"
Specify the location that the packages downloaded by apt
should be cached.
Setting this value to "" will cause caching to be 
turned off.

.TP
.BI "APTCACHEHARDLINK=" "yes"
Specify using hard links in apt cache handling.
Changing this to no will disable hard linking and will
copy the files.

It is advised to set this to 
.B "no"
if you are using user-mode-linux.

.TP
.BI "REMOVEPACKAGES=" "lilo"
Specify the packages to be removed on creation of 
.B base.tgz
Leaving lilo in the chroot is like keeping a timebomb...

.TP
.BI "HOOKDIR=" "/usr/lib/pbuilder/hooks"
Specifies the default location for the user hooks
directory. 
This is overridden with the option 
.BR "--hookdir" "."

If this is specified, hooks are searched for in
the chroot, when running 
.BR "pbuilder" "."
If it is not defined, or is an empty string, 
hooks are not executed.

For details, see 
.B "pbuilder.1"

.TP
.BI "DEBEMAIL=" "Maintainer Name <Mail@Address>"

If this was specified, 
.B dpkg-buildpackage
command will be passed with the necessary sponsorship option 
.B "-mMaintainer Name <Mail@Address>"
on building.
Overridden with 
.B "--debemail"
command-line option.

The default configuration for 
.B pbuilder
is empty for this value.

.TP
.BI "DEBBUILDOPTS=" ""

The options given here will be passed on to
.BR dpkg-buildpackage .
This can be useful e.g. for binary-only builds. The command-line option
.B "--debbuildopts"
overrides any contents specified here.
The default value is to build source and binary package.

.TP
.BI "BUILDSOURCEROOTCMD=" "fakeroot"

This option is used on invocation of fakeroot 
for 
.B "dpkg-buildpackage"
in 
.B "pdebuild"

.TP
.BI "PBUILDERROOTCMD=" "sudo"

This option is used on invocation of 
.B "pbuilder build"
in 
.B "pdebuild"

.TP
.BI "BUILDUSERID=" "1234"
The uid to be used inside chroot.
It should not collide with user-id outside the chroot.

.TP
.BI "BUILDUSERNAME=" "pbuilder"
The user name of the user the build will run as.
Specifying this will enable the use of fakeroot inside 
pbuilder.

Note that this will require fakeroot to be installed within
the chroot, and fakeroot will automatically be installed.
And 
.B "-rfakeroot"
will be added to
.B "DEBBUILDOPTS"

.TP
.BI "APTCONFDIR=" "/etc/apt"
Configures where the apt configuration files are copied from.
By default, this value is empty,
allowing the usual configuration options
to take effect.
Setting this variable overrides other options.

.TP
.BI "TIMEOUT_TIME=" "2h"
Sets timeout time.
Build will be stoped with SIGTERM after the set time.

.TP
.BI "export DEBIAN_FRONTEND=" "noninteractive"
Sets interactiveness of pbuilder run.
Setting this value to blank will cause the 
pbuilder run to be interactive.
Change this value when noninteractive upgrades 
do not work.

.TP
.BI "USEDEVFS=" "no"
Whether to use DEVFS or not.

.TP
.BI "BUILDRESULTUID="
.TP
.BI "BUILDRESULTGID="
Set the UID and GID of the files built as result.
They probably need to be set to numeric UID values,
so that it works the same inside the chroot and outside the 
chroot.

.TP
.BI "AUTO_DEBSIGN=" "yes"
When this value is set to yes, 
.B pdebuild 
will invoke debsign command after building.


.TP
.BI "BINDMOUNTS=" "directories-to-bind-mount"
When this value is set, pbuilder will mount these directories using
bind-mount.

Example:
.B "BINDMOUNTS=""/home /mnt/test """

Do not bind-mount 
.B "/"

.TP
.BI "USE_PDEBUILD_INTERNAL=" "yes"
When this option is set to
.I yes
.B "pdebuild-internal"
implementation of 
.B pdebuild
is used.

.TP
.BI "DEBOOTSTRAPOPTS=" "'--variant=buildd'"
When this option is set to 
.B "--variant=buildd"
.B "pbuilder"
will invoke 
.B "debootstrap" 
with "--variant=buildd"
option, which results in debootstrap creating a minimal chroot for 
buildd instead of trying to create a minimal installation chroot.

.SH "AUTHOR"
Initial coding, and main maintenance is done by 
Junichi Uekawa <dancer@debian.org>.
User hooks code added by Dale Amon <amon@vnl.com>

The homepage is available at
.B "\%http://www.netfort.gr.jp/~dancer/software/pbuilder.html"

.SH "FILES"
.I "/etc/pbuilderrc, ${HOME}/.pbuilderrc"
.SH "SEE ALSO"
.RI "pbuilder (" 8 "), "
.RI "pdebuild (" 1 ")"

