#! /bin/bash
# pbuilder by Junichi Uekawa <dancer@debian.org> 2001 Aug 25
# Copyright 2001 Junichi Uekawa
#Distributed under GPL version 2 or later

set -e 

test -z "$1" && (
    . /usr/lib/pbuilder/pbuilder-modules
    showhelp
)

case "$1" in
    create)
	shift;
	/usr/lib/pbuilder/pbuilder-createbuildenv $@
	;;
    update)
	shift ;
	/usr/lib/pbuilder/pbuilder-updatebuildenv $@
	;;
    build)
	shift ;
	/usr/lib/pbuilder/pbuilder-buildpackage $@
	;;
    clean)
	. /etc/pbuilderrc
	echo "Cleaning [$BUILDPLACE]"
	test -n "$BUILDPLACE" && rm -rf "$BUILDPLACE"/* || true
	echo "Cleaning [$APTCACHE]"
	test -n "$APTCACHE" && rm -rf "$APTCACHE"/* || true
	;;
    login)
	shift 
	. /usr/lib/pbuilder/pbuilder-checkparams
	extractbuildplace
	echo " -> entering the shell"
	chroot "$BUILDPLACE" bin/bash
	umountproc
	cleanbuildplace
	;;
    *)
	. /usr/lib/pbuilder/pbuilder-modules
	showhelp
	;;
esac

