#! /bin/bash

set -e 

. /usr/lib/pbuilder/pbuilder-checkparams
. /usr/lib/pbuilder/pbuilder-runhooks

function abortprocess () {
# function to do the aborting process in pbuilder-updatebuildenv
    umountproc
    cleanbuildplace    
}

CHROOTEXEC="chroot $BUILDPLACE "

test -n "$DISTRIBUTION" && echo "Upgrading for distribution $DISTRIBUTION" 

extractbuildplace

if [ -n "$HOOKDIR" ]; then
    loadhooks
fi
echo "Refreshing the base.tgz "
echo " -> upgrading packages"
$CHROOTEXEC /usr/bin/apt-get update || abortprocess
$CHROOTEXEC /usr/bin/dpkg --purge lilo || abortprocess
$CHROOTEXEC /usr/bin/apt-get -y dist-upgrade || abortprocess
$CHROOTEXEC /usr/bin/apt-get -y install build-essential dpkg-dev apt $EXTRAPACKAGES || abortprocess
$CHROOTEXEC /usr/bin/apt-get clean || abortprocess

if [ -n "$HOOKDIR" ]; then
    executehooks "X"
    unloadhooks
fi

umountproc
echo " -> creating base.tgz"
(cd "$BUILDPLACE"; tar cfz "$BASETGZ" *)
cleanbuildplace
