#! /bin/bash 
# this is sourced from pbuilder packages to process the optional parameters.

. /etc/pbuilderrc

while [ -n $1 ]; do
  case "$1" in 
    --basetgz) 
      BASETGZ=$(readlink -f "$2");
      shift; shift;
      ;;
    --buildplace)
      BUILDPLACE=$(readlink -f "$2");
      shift; shift;
      ;;
    --mirror)
      MIRROR="$2";
      shift; shift;
      ;;
    --http-proxy)
      export http_proxy="$2";
      shift; shift;
      ;;
    --distribution)
      DISTRIBUTION="$2";
      shift; shift;
      ;;
    --buildresult)
      BUILDRESULT=$(readlink -f "$2");
      shift; shift;
      ;;
    --help)
      cat <<EOF
Command Line Options:
 --basetgz [base.tgz location]
 --buildplace [location of build]
 --mirror [mirror location]
 --http-proxy [proxy]
 --distribution [distribution(woody/sid)]
 --buildresult [location-to-copy-build-result]
EOF
      exit 1;
      ;;
    *)
      break;
      ;;
  esac
done

