.TH "pdebuild" 1 "2006 May 24" "Debian" "pbuilder"
.SH NAME
pdebuild \- pbuilder way of doing debuild
.SH SYNOPSIS
.BI "pdebuild [" "pdebuild options" "] \-\- [" "pbuilder options" "]"
.PP
.SH DESCRIPTION
A convenience program for 
.B "pbuilder"
which invokes pbuilder after obtaining appropriate root privilege 
in a Debian source directory.
One must be inside the source tree containing the
.B "debian"
directory, in order to make it work.

.SH "PDEBUILD OPTIONS"

The first option is always the operation to be done.
It is followed by options of the form
.BI "\-\-" "option name"
which will modify the semantics as explained below.
They are applied from left-to-right, and when there are 
conflicting options, the rightmost options will have effect.

.TP
.BI "\-\-buildsourceroot [" "fakeroot" "]"
The command used to gain root privilege for 
invoking dpkg-buildpackage

.TP
.BI "\-\-pbuilderroot [" "sudo" "]"
The command used to gain root privilege for 
invoking pbuilder.

.TP
.BI "\-\-pbuildersatisfydepends [" "/usr/lib/pbuilder/pbuilder-satisfydepends" "]"
The command used to satisfy (i.e. install) build-dependencies.

.TP
.BI "\-\-auto\-debsign"

Invoke debsign at the end of pdebuild process.

.TP
.BI "\-\-debsign\-k [" "key\-id" "]"
Pass 
.B \-k
option to debsign to specify which key-id to sign.

.TP
.BI "\-\-buildresult [" "Directory for build results" "]"

The place which build result is stored.

Note that for pdebuild, buildresult needs to be specified as pdebuild
option in the command-line, not as pbuilder option.

Note that the default value for buildresult is what is defined for
pbuilder,
.B "/var/cache/pbuilder/result"
and not 
.B ".."

.TP
.BI "\-\-configfile [" "Extra config file to use" "]"

The configuration file is used, and passed on to
.BR "pbuilder" .

.TP
.BI "\-\-debbuildopts [" "options to pass to dpkg-buildpackage" "]"

The space-delimited list of options are passed to dpkg-buildpackage.
This option overrides pbuilder option 
.B "\-\-debbuildopts"

Multiple options are delimited with spaces.

.TP
.BI "\-\-use\-pdebuild\-internal"
Uses a different implementation of pdebuild, which calls clean and build inside 
the chroot, using bind-mounts.

.B "pdebuild\-internal"
tries to run debian/rules clean inside the chroot.
To achieve the goal, the working directory is passed on inside the chroot,
in the form of bind-mounting and
.B debuild 
is run.

This option will not protect the working directory and its parent directories 
from the build scripts.

.TP
.BI "\-\-logfile [" "file to log" "]"
Specifies the logfile to create. 
The messages generated during execution will be written to the file, 
instead of messages coming to the 
standard output.

.TP
.BI "\-\-pbuilder [" "pbuilder" "]"
Specifies which command to invoke as pbuilder.

.TP
.BI "\-\-help"

Show a brief help message.

.TP
.BI "\-\- [" "pbuilder options" "]"

After the 
.B "\-\-"
symbol, an arbitrary number of pbuilder options can be specified.
See pbuilder.8 for full list of options.


There is an exception that
.B "\-\-buildresult"
needs to be specified as pdebuild option before the 
.B "\-\-"
to be effective.

.SH "FILES"
.TP
.I "/etc/pbuilderrc"
The configuration file for pbuilder, used in pdebuild.

.TP
.I "/usr/share/pbuilder/pbuilderrc"
The default configuration file for pbuilder, used in pdebuild.

.TP
.I "${HOME}/.pbuilderrc"
Configuration file for pbuilder, used in pdebuild,
overrides what is written in
.B /etc/pbuilderrc


.SH "EXAMPLES"

.TP
.B "pdebuild"

.nf
$ pwd
/home/dancer/DEBIAN/cowdancer/cowdancer
$ ls debian/rules
debian/rules
$ pdebuild
W: /home/dancer/.pbuilderrc does not exist
dpkg-buildpackage: source package is cowdancer
dpkg-buildpackage: source version is 0.26
dpkg-buildpackage: source changed by Junichi Uekawa <dancer@debian.org>
dpkg-buildpackage: source version without epoch 0.26
 fakeroot debian/rules clean
dh_testdir
dh_testroot
rm -f build-stamp configure-stamp
/usr/bin/make clean
make[1]: Entering directory `/home/dancer/DEBIAN/cowdancer/cowdancer'
rm -f *~ *.o *.lo libcowdancer.so cow-shell cowbuilder
make[1]: Leaving directory `/home/dancer/DEBIAN/cowdancer/cowdancer'
dh_clean
 dpkg-source -b cowdancer
dpkg-source: warning: source directory `./cowdancer' is not <sourcepackage>-<upstreamversion> `cowdancer-0.26'
dpkg-source: building cowdancer in cowdancer_0.26.tar.gz
	.
	.
	.
.hy

.SH "BUGS"

pdebuild will accept all options that pbuilder accepts as pdebuild
option.  However, unless the option is documented in the manual page,
it may be ignored.

.SH "AUTHOR"
Initial coding, and main maintenance is done by 
Junichi Uekawa <dancer@debian.org>.

The homepage is available at
.B "\%http://www.netfort.gr.jp/~dancer/software/pbuilder.html"

.SH "SEE ALSO"
.BR "pbuilder" "(8), "
.BR "pbuilderrc" "(5)"

\"  LocalWords:  pdebuild pbuilder debuild debian debsign buildresult
