#! /bin/bash
set -e

while ! test -d ./debian -o "$(pwd)" = "/" ; do
    cd ..;
done

if test ! -d ./debian; then
    echo "Cannot find ./debian dir"
    exit 1
fi;

. /usr/lib/pbuilder/pbuilder-checkparams
dpkg-buildpackage -S -us -uc -r$BUILDSOURCEROOTCMD || true
$PBUILDERROOTCMD pbuilder build "$@" ../$(dpkg-parsechangelog|sed -n 's/^Source: //p')_$(dpkg-parsechangelog|sed -n 's/^Version: \(.*:\|\)//p').dsc

