.TH "pdebuild" 1 "2002 Sep 25" "Debian" "pbuilder"
.SH NAME
pdebuild \- pbuilder way of doing debuild
.SH SYNOPSIS
.BI "pdebuild [" "pdebuild options" "] -- [" "pbuilder options" "]"
.PP
.SH DESCRIPTION
A convenience program for 
.B pbuilder
which invokes pbuilder after obtaining appropriate root privilate 
in a Debian source directory.
One must be inside the source tree containing the
.B debian
directory, in order to make it work.

.SH "PDEBUILD OPTIONS"
.TP
.BI "--buildsourceroot [" "fakeroot" "]"
The command used to gain root privilege for 
invoking dpkg-buildpackage

.TP
.BI "--pbuilderroot [" "sudo" "]"
The command used to gain root privilege for 
invoking pbuilder.

.TP
.BI "--auto-debsign"

Invoke debsign at the end of pdebuild process.

.TP
.BI "--debsign-k [" "key-id" "]"
Pass 
.B -k
option to debsign to specify which keyid to sign.

.TP
.BI "--buildresult [" "Directory for build results" "]"

The place which build result is stored.

Note that for pdebuild, the setting for buildresult needs to be specified
here in the command-line.

.TP
.BI "--configfile [" "Extra config file to use" "]"

The configuration file is used, and passed on to 
.BR "pbuilder" .

.TP
.BI "--debbuildopts [" "options to pass to dpkg-buildpackage" "]"

The space-delimited list of options are passed to dpkg-buildpackage.
This option overrides pbuilder option 
.B "--debbuildopts"

.TP
.BI "--use-pdebuild-internal"
Uses a different implementation of pdebuild, which calls clean and build inside 
the chroot, using bind-mounts.

.B "pdebuild-internal"
tries to run debian/rules clean inside the chroot.
To achieve the goal, the working directory is passed on inside the chroot,
in the form of bind-mounting and
.B debuild 
is run.

This option will not protect the working directory and its parent directories 
from the build scripts.

.TP
.BI "--logfile [" "file to log" "]"
Specifies the logfile to create. 
The messages generated during execution will be written to the file, 
instead of messages coming to the 
standard output.

.TP
.BI "-- [" "pbuilder options" "]"

After the 
.B "--"
symbol, an arbitrary number of pbuilder options can be specified.
See pbuilder.8 for full list of options.


There is an exception that
.B "--buildresult"
needs to be specified as pdebuild option before the 
.B "--"
to be effective.

.SH "FILES"
.TP
.I "/etc/pbuilderrc"
The configuration file for pbuilder, used in pdebuild.

.TP
.I "/usr/share/pbuilder/pbuilderrc"
The default configuration file for pbuilder, used in pdebuild.

.TP
.I "${HOME}/.pbuilderrc"
Configuration file for pbuilder, used in pdebuild,
overrides what is written in
.B /etc/pbuilderrc

.SH "BUGS"
pdebuid will accept all options that pbuilder accepts as 
pdebuild option.
However, unless the option is documented in the manual page, it 
may be ignored.

.SH "AUTHOR"
Initial coding, and main maintenance is done by 
Junichi Uekawa <dancer@debian.org>.

The homepage is available at
.B "http://www.netfort.gr.jp/~dancer/software/pbuilder.html"

.SH "SEE ALSO"
.RI "pbuilder (" 8 "), "
.RI "pbuilderrc (" 5 ") "
