#!/bin/bash

if [ -n "$PBUILDER_CHECKOUT" ]; then
    . "$PBUILDER_CHECKOUT/testlib.sh"

    . "$PBUILDER_CHECKOUT/pbuilder-modules"
else
    # these currently don't need to be exported
    PBUILDER_TEST_ROOT="${PBUILDER_ROOT:-}"
    PBUILDER_TEST_PKGLIBDIR="${PBUILDER_PKGLIBDIR:-$PBUILDER_ROOT/usr/lib/pbuilder}"
    . "$PBUILDER_TEST_PKGLIBDIR/testlib.sh"

    . "$PBUILDER_TEST_PKGLIBDIR/pbuilder-modules"
fi

function test_information() {
    log "I: test"
    log "W: warning"
    log "E: error"
}
expect_output "I: test
W: warning
E: error" test_information

testlib_summary
