#!/bin/bash

. ./testlib.sh
. ./pbuilder-satisfydepends-funcs

# testsuite to test pbuilder-satisfydepends-funcs.

DEBIAN_CONTROL=""

cleanup() {
    if [ -n "$DEBIAN_CONTROL" ]; then
        rm -f "$DEBIAN_CONTROL"
    fi
}

test_get_control_re() {
    cat <<EOF >"$DEBIAN_CONTROL"
Source: amule
XXXX:
Build-Depends: 
 autotools-dev,
 debhelper,
 quilt,
##
 libwxgtk2.8-dev
Build-Depends-Indep: test, test1, 
 test2, test3 | 
 test4, test5
Misc: test

Build-Depends: wrong build depends, line
Description: test
 other things
 wow
EOF
    get_control_re "$DEBIAN_CONTROL" "build-(depends|depends-indep)"
}

trap cleanup sigpipe sighup exit

# TODO move to build dir
DEBIAN_CONTROL="$(tempfile)"

expect_output "  autotools-dev, debhelper, quilt, libwxgtk2.8-dev
 test, test1,  test2, test3 |  test4, test5" test_get_control_re

testlib_summary
