#!/bin/bash

. ./testlib.sh

# testsuite for pbuilder-checkparams

test_debuildopts() {
    # stderr is redirected to /dev/null to avoid failing if ~/.pbuilderrc is
    # missing (this outputs a warning which is not expected in the output)
    . ./pbuilder-checkparams
    echo "$DEBBUILDOPTS"
}

# setup a fake installed environment
trap testlib_cleanup_env sigpipe sighup exit
testlib_setup_env

expect_output "" \
    test_debuildopts foo.dsc
expect_output "" \
    test_debuildopts --debbuildopts "" foo.dsc
expect_output "-v1.0 -efoo" \
    test_debuildopts --debbuildopts "-v1.0 -efoo" foo.dsc
expect_output "-v1.0 -efoo" \
    test_debuildopts --debbuildopts -v1.0 --debbuildopts -efoo foo.dsc
expect_output "-efoo" \
    test_debuildopts --debbuildopts -v1.0 --debbuildopts "" --debbuildopts -efoo foo.dsc

testlib_summary
