#!/bin/bash

mkdir /tmp/test-work
cd /tmp/test-work
cp /etc/apt/sources.list{,-}
sed 's/#deb-src/deb-src/' < /etc/apt/sources.list- > /etc/apt/sources.list
apt-get update
apt-get source dsh
LD_PRELOAD= pbuilder build dsh*dsc
